name: Test

on: push

jobs:
  test:
    uses: "KyoriPowered/.github/.github/workflows/shared-action-test.yaml@trunk"
    secrets: "inherit"

  functional-test:
    runs-on: ubuntu-latest
    steps:
    - uses: "actions/checkout@v4.1.1"
    - name: "Run regex match"
      uses: ./
      id: test-run
      with:
        text: "release/2.x"
        regex: 'release/([\d.x]+)'
    - name: "Validate output"
      env:
        MATCH: ${{ steps.test-run.outputs.match }}
        GROUP_1: ${{ steps.test-run.outputs.group1 }}
      run: |
        FAILED=0
        if [[ "$MATCH" != "release/2.x" ]]; then
          echo "::error title=Functional test failure::Wrong value for match, got '$MATCH' but expected 'release/2.x'"
          FAILED=1
        fi
        if [[ "$GROUP_1" != "2.x" ]]; then
          echo "::error title=Functional test failure::Wrong value for group 1, got '$GROUP_1' but expected '2.x'"
          FAILED=1
        fi

        if [[ "$FAILED" -eq 1 ]]; then
          exit 1
        fi
